#include "stdafx.h"

#ifdef _DEBUG
#pragma comment(lib, "LowLevelDEBUG.lib")
#pragma comment(lib, "LowLevelClothDEBUG.lib")
#pragma comment(lib, "PhysX3DEBUG_x64.lib")
#pragma comment(lib, "PhysX3CharacterKinematicDEBUG_x64.lib")
#pragma comment(lib, "PhysX3CommonDEBUG_x64.lib")
#pragma comment(lib, "PhysX3CookingDEBUG_x64.lib")
#pragma comment(lib, "PhysX3ExtensionsDEBUG.lib")
#pragma comment(lib, "PhysX3VehicleDEBUG.lib")
#pragma comment(lib, "PhysXProfileSDKDEBUG.lib")
#pragma comment(lib, "PhysXVisualDebuggerSDKDEBUG.lib")
#pragma comment(lib, "PvdRuntimeDEBUG.lib")
#pragma comment(lib, "PxTaskDEBUG.lib")
#pragma comment(lib, "SceneQueryDEBUG.lib")
#pragma comment(lib, "SimulationControllerDEBUG.lib")
#else
#pragma comment(lib, "LowLevel.lib")
#pragma comment(lib, "LowLevelCloth.lib")
#pragma comment(lib, "PhysX3_x64.lib")
#pragma comment(lib, "PhysX3CharacterKinematic_x64.lib")
#pragma comment(lib, "PhysX3Common_x64.lib")
#pragma comment(lib, "PhysX3Cooking_x64.lib")
#pragma comment(lib, "PhysX3Extensions.lib")
#pragma comment(lib, "PhysX3Vehicle.lib")
#pragma comment(lib, "PhysXProfileSDK.lib")
#pragma comment(lib, "PhysXVisualDebuggerSDK.lib")
#pragma comment(lib, "PvdRuntime.lib")
#pragma comment(lib, "PxTask.lib")
#pragma comment(lib, "SceneQuery.lib")
#pragma comment(lib, "SimulationController.lib")
#endif

#ifdef _DEBUG
#pragma comment(lib, "APEX_ClothingDEBUG_x64.lib")
#pragma comment(lib, "APEX_DestructibleDEBUG_x64.lib")
#pragma comment(lib, "APEX_EmitterDEBUG.lib")
#pragma comment(lib, "APEX_LegacyDEBUG_x64.lib")
#pragma comment(lib, "APEX_LoaderDEBUG_x64.lib")
#pragma comment(lib, "ApexCommonDEBUG.lib")
#pragma comment(lib, "ApexFrameworkDEBUG_x64.lib")
#pragma comment(lib, "ApexSharedDEBUG.lib")
#else
#pragma comment(lib, "APEX_Clothing_x64.lib")
#pragma comment(lib, "APEX_Destructible_x64.lib")
#pragma comment(lib, "APEX_Emitter.lib")
#pragma comment(lib, "APEX_Legacy_x64.lib")
#pragma comment(lib, "APEX_Loader_x64.lib")
#pragma comment(lib, "ApexCommon.lib")
#pragma comment(lib, "ApexFramework_x64.lib")
#pragma comment(lib, "ApexShared.lib")
#endif